[package]
name = "faucet"
edition = "2021"
version = "0.1.0"
license = "MIT"
description = "The Contract for Faucet platform"

[lib]
crate-type = ["cdylib"]


[dependencies]
near-sdk = "4.1.1"
unidecode = "0.3.0"
near-units = "0.2.0"